apiVersion: v1
kind: Service
metadata:
  name: employeesapi-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30009
  selector:
    app: employeesapi
