apiVersion: v1
kind: Service
metadata:
  name: dotnetcoremvcclient-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    app: dotnetcoremvcclient
